name: dust-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - scikit-learn
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - minisom
  - xarray
  - mystmd
